#! /usr/bin/php
<?php

// Load shared functionality.
require 'hooks/shared.php';

$stdin = fopen('php://stdin', 'r');
$payload = array(
  'uid' => $pusher_uid,
  'repo_id' => $repo_id,
  'git hook' => 'post-receive',
  'data' => stream_get_contents($stdin),
  'timestamp' => time(),
);
fclose($stdin);

_githooks_enqueue_job('versioncontrol_git_repo_parsing', $payload);
